### ISSUE TITLE
Use google for web search

### ISSUE THREAD

**Issue by nadavkav** [segeybutakov/moodle-plagiarism_crot#1]
Hello Segey,

How about using Google search API to search the Web?

Nadav.

**Comment by nadavkav** [comment]
Can you direct me to where I should start digging in the code, to make it
work?

**Comment by segeybutakov** [comment]
that would be here:
https://github.com/segeybutakov/moodle-plagiarism_crot/blob/master/locallib.php#L268

You'll need to change url and parse duckduckgo reply format.

**Comment by nadavkav** [comment]
Thanks! looking into it...
